# H2 Database
spring.datasource.url=jdbc:h2:mem:property_test
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=


# Recreate database for every test
spring.jpa.hibernate.ddl-auto=create-drop


# No SQL spam
spring.jpa.show-sql=false


# Disable unnecessary logs
logging.level.root=WARN