# Production database
spring.datasource.url=jdbc:mysql://localhost:3306/property_prod?useSSL=true&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=password


# Never change schema automatically
spring.jpa.hibernate.ddl-auto=validate


# Hide SQL
spring.jpa.show-sql=false


# Production logging
logging.level.root=INFO
logging.file.path=logs/prod


# Disable detailed errors
server.error.include-message=never
server.error.include-stacktrace=never