# Acceptance database
spring.datasource.url=jdbc:mysql://localhost:3306/property_acceptance?useSSL=false&serverTimezone=UTC

spring.datasource.username=root
spring.datasource.password=


# Never modify database automatically
spring.jpa.hibernate.ddl-auto=validate


# Less logging than development
spring.jpa.show-sql=false


logging.level.root=INFO