spring.application.name=property-management

server.port=8080

# JPA common settings
spring.jpa.properties.hibernate.format_sql=true

# Jackson JSON settings
spring.jackson.serialization.fail-on-empty-beans=false

# Profile (change this depending on environment)
spring.profiles.active=prod

server.error.include-message=always

