# Database
spring.datasource.url=jdbc:mysql://localhost:3306/property_dev?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=password


# Hibernate
spring.jpa.hibernate.ddl-auto=update

# Show generated SQL
spring.jpa.show-sql=true


# Logging
logging.level.org.springframework.web=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE